# Generated by Django 3.1.2 on 2020-12-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books2', '0003_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='image',
        ),
    ]
